spring:
  datasource:
    url: jdbc:mysql://rds613943t1x67vo5hw7o.mysql.rds.aliyuncs.com:3306/sachet?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: sachet_dbuser
    password: dQyMJHXT7rrvkp2R
    filters: wall,mergeStat



#多数据源情况的配置
guns:
  muti-datasource:
    open: false
    url: jdbc:mysql://rds613943t1x67vo5hw7o.mysql.rds.aliyuncs.com:3306/sachet?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: sachet_dbuser
    password: dQyMJHXT7rrvkp2R
    dataSourceNames:
    - dataSourceGuns
    - dataSourceBiz